creation_rules:
  # Encrypt secrets in all paths
  - path_regex: .*\.sops\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: >-
      age1v9eqrfhwu8cxtmtdydkhc53dh9rr2e3evk6ydk86mymf8htwdsasflr2jx
  # Also catch any file with 'secret' in the name
  - path_regex: .*secret.*\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: >-
      age1v9eqrfhwu8cxtmtdydkhc53dh9rr2e3evk6ydk86mymf8htwdsasflr2jx