creation_rules:
  # Encrypt secrets in all paths
  - path_regex: .*\.sops\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: >-
      mykey
  # Also catch any file with 'secret' in the name
  - path_regex: .*secret.*\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: >-
      mykey