apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: merox-ip-pool
  namespace: kube-system
spec:
  blocks:
  - start: "10.57.57.99"
    stop: "10.57.57.109"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: merox-l2-policy
  namespace: kube-system
spec:
  # Selectează toate serviciile LoadBalancer
  serviceSelector: {}
  # Exclude control plane nodes dacă ai 
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/control-plane
      operator: DoesNotExist
  # Interface-urile de rețea pentru anunțuri L2
  interfaces:
  - ^eth[0-9]+
  - ^ens[0-9]+
  - ^enp[0-9]+s[0-9]+
  externalIPs: true
  loadBalancerIPs: true