apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-test
  namespace: nginx-test
spec:
  interval: 30m
  chart:
    spec:
      chart: nginx
      version: "18.x.x"
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: flux-system
  values:
    # Replica count
    replicaCount: 2
    
    # Image configuration
    image:
      registry: docker.io
      repository: bitnami/nginx
      tag: "1.27"
      pullPolicy: IfNotPresent
    
    # Service configuration
    service:
      type: ClusterIP
      ports:
        http: 80
    
    # Resources
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
    
    # Custom index page
    staticSiteConfigmap: nginx-test-content
    
    # Pod security context
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1001
      fsGroup: 1001
    
    # Container security context
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1001
    
    # Health checks
    livenessProbe:
      httpGet:
        path: /
        port: http
      initialDelaySeconds: 30
      periodSeconds: 30
      timeoutSeconds: 5
      
    readinessProbe:
      httpGet:
        path: /
        port: http
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 3