apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-config
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: cert-manager-install
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/configs/cert-manager
  prune: true
  wait: true
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
